
drop table if exists posting cascade;

create table posting (
    id bigint generated by default as identity,
    posted_at timestamp(6),
    content varchar(255),
    password varchar(255),
    posted_by varchar(255),
    title varchar(255),
    primary key (id)
);