name: Build And Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: build/libs/demo-0.0.1-SNAPSHOT.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: application
        path: build/libs/

    - name: Deploy to EC2
      run: |
        echo "$EC2_SSH_KEY" > private_key.pem
        chmod 400 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/demo-0.0.1-SNAPSHOT.jar.jar $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/app.jar
        ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "pgrep java | xargs kill -9; nohup java -jar /home/$EC2_USERNAME/app.jar > app.log 2>&1 &"
        rm -f private_key.pem
    
